### ISSUE TITLE
Adding checkpointing for storing Axon Networks to disk

### ISSUE THREAD

**Issue by siboehm** [emer/axon#114]
There seems to be no way currently to save an Axon model to disk in a way that includes all the state of the model. This would be useful for saving & restoring checkpoints for long training runs.

We have a [NetworkBase.WriteWtsJSON](https://github.com/siboehm/axon/blob/c96f1bd94bac79ca47795d391632a74191838642/axon/networkbase.go#L522) which writes the Synapse weights, some members of Layer.ActAvg, as well as each Neuron's TrgAvg and ActAvg. But this is far from capturing all the state of the network. I currently work around it by also dumping the Neuron slice to disk, but that may still not be all the state.

I'm unsure if we want to extend WriteWtsJSON, since serializing floats to string is either lossy or space-inefficient. We could use BSON, but upon first glance it doesn't seem to support fp32, but at current model sizes that shouldn't really matter. Probably we're fine with something akin to Python pickle, meaning the serialized Network will only work with one specific version of Axon.

**Comment by rcoreilly** [comment]
You only need to save the weights for checkpointing.  This is done in LVis for example which takes a long time to run.  It saves all the state required to then be able to resume training where it left off.  You never really need to save the current activity state.

**Comment by garymm** [comment]
For reference, `Network.OpenWtsJSON` and `Network.SaveWtsJSON`.
