### ISSUE TITLE
Add a way to specify the random seed

### ISSUE THREAD

**Issue by siboehm** [emer/axon#115]
Useful for reproducible testing, and for initializing two networks with exactly the same initial state. Is it enough to just call `rand.Seed(<seed>)` before initializing the network or are we getting entropy from somewhere else as well?

One option: store a `rand.Source` on the layer / network, and pull all our entropy from there. That way we're not relying on global state.

**Comment by rcoreilly** [comment]
All the sims typically have a set of seeds stored for each Run, and set the seed in NewRun, so that the entire sequence of runs is reproducible in principle.  Boa is doing this -- see sim.go InitRndSeed() and related calls.

**Comment by siboehm** [comment]
Yes you're right, I think we can close this. I looked for usages of `rand` in the code (though they may not capture all randomness, as calls to rand may be hidden in other packages):
- GiBase + GiBase, called during InitAct
- InitWtsSyn, call during InitWts
- SWtFmWt, called during SlowAdapt

So by specifying `rand.Seed` before I create the model, I can indeed create two perfectly equal models. Thanks!
