### ISSUE TITLE
2 Questions

### ISSUE THREAD

**Issue by siboehm** [emer/axon#122]
During PR review of my (merged) PR #116 we came up with two questions:

1. Why is Spike a float32 here? We use it as a bool everywhere in the code. May make sense to refactor it unless there's good reason not to (it probably makes your reflection code easier to write?)
https://github.com/emer/axon/blob/d1144d2768ebf4b6e5e3946c58a56682c83b0b5d/axon/neuron.go#L30

2. What's the special purpose of `ly.Pool[0]` that it's treated so differently?
https://github.com/emer/axon/blob/d1144d2768ebf4b6e5e3946c58a56682c83b0b5d/axon/layer.go#L1294-L1297

**Comment by rcoreilly** [comment]
1. The entire API for viewing Neuron vars is based on float32 -- NetView expects these.  Also, for GPU, it is essential to have everything as 32bit vals.
2. Pool[0] represents the entire layer -- it always exists and is always updated.  sub-pools are optional (4D layers).

**Comment by siboehm** [comment]
Thanks! Will add comments. 

Last question: Why do we update the inhibitory ring buffer only for non-inhibitory neurons? I'd have expected it to be the other way around.
https://github.com/emer/axon/blob/408c4f4620c9a9f915f50bb1cdcab525737fef32/axon/prjn.go#L712-L714

**Comment by rcoreilly** [comment]
inhibitory projections directly drive GiSyn with their spikes, so they are excluded from the computed FS-FFFB inhibition that is driven from this PIBuf value.

**Comment by siboehm** [comment]
Got it. I should check the struct annotations more often, I forget about them since VSCode doesn't show them when I hover of the variable (unlike normal comments).
