### ISSUE TITLE
Threads.SynCa and SynCaFun no longer needed (after GPU PR merge)

### ISSUE THREAD

**Issue by rcoreilly** [emer/axon#172]
SynCaSend and SynCaRecv are now using NeuronFun. Could do some further experimentation to see if it might somehow be beneficial to use fewer threads via SynCa param but I doubt that would be the case..

Also is there any benefit to using this strategy on CPU too: https://github.com/emer/axon/issues/171 ?

**Comment by rcoreilly** [comment]
@siboehm are you planning to take another pass through threading, including updating DWt to go per-neuron or per-synapse? If so, this can be done in that context..

**Comment by rcoreilly** [comment]
@siboehm are you planning to take another pass through threading, including updating DWt to go per-neuron or per-synapse? If so, this can be done in that context..

**Comment by siboehm** [comment]
I want to get data parallel finished first, but after that I'll take a look at this again, won't be a very complicated change.

**Comment by rcoreilly** [comment]
everything is neuron parallel and using the same NThreads param -- much simpler.
