### ISSUE TITLE
crash when zooming out / in the 3D view

### ISSUE THREAD

**Issue by etuleu** [emer/axon#319]
To reproduce run boa, start training and zoom out in the 3D maze view.

> goroutine 162 [runnable]:
runtime.cgocall(0x1054969f8, 0x14037514548)
	/opt/homebrew/Cellar/go/1.21.1/libexec/src/runtime/cgocall.go:157 +0x44 fp=0x14037514500 sp=0x140375144c0 pc=0x10453f7d4
github.com/goki/vulkan._Cfunc_callVkGetImageMemoryRequirements(0x13e8a5618, 0x13e631640, 0x600002704fe0)
	_cgo_gotypes.go:9255 +0x30 fp=0x14037514540 sp=0x14037514500 pc=0x1048ac610
github.com/goki/vulkan.GetImageMemoryRequirements.func1(0x13e8a5618, 0x13e631640, 0x8?)
	/Users/erdal/go/pkg/mod/github.com/goki/vulkan@v1.0.6/vulkan.go:302 +0x90 fp=0x14037514590 sp=0x14037514540 pc=0x1048d4f20
github.com/goki/vulkan.GetImageMemoryRequirements(0x13e8a5618, 0x13e631640, 0x13e75e6e0?)
	/Users/erdal/go/pkg/mod/github.com/goki/vulkan@v1.0.6/vulkan.go:302 +0x48 fp=0x140375145d0 sp=0x14037514590 pc=0x1048d4e58
github.com/goki/vgpu/vgpu.(*Image).AllocImage(0x1400025bd18)
	/Users/erdal/go/pkg/mod/github.com/goki/vgpu@v1.0.33/vgpu/image.go:726 +0x1c8 fp=0x140375154a0 sp=0x140375145d0 pc=0x10490bed8
github.com/goki/vgpu/vgpu.(*Image).SetSize(0x1400025bc88?, {0x3?, 0xb1fc716ebb9aef83?})
	/Users/erdal/go/pkg/mod/github.com/goki/vgpu@v1.0.33/vgpu/image.go:661 +0x8c fp=0x140375154c0 sp=0x140375154a0 pc=0x10490bcdc
github.com/goki/vgpu/vgpu.(*Render).SetSize(0x1400025bc58?, {0x10454f098?, 0x14037515528?})
	/Users/erdal/go/pkg/mod/github.com/goki/vgpu@v1.0.33/vgpu/render.go:194 +0x70 fp=0x14037515500 sp=0x140375154c0 pc=0x1049148d0
github.com/goki/vgpu/vgpu.(*RenderFrame).ReConfig(0x14000752fc0)
	/Users/erdal/go/pkg/mod/github.com/goki/vgpu@v1.0.33/vgpu/renderframe.go:126 +0x30 fp=0x14037515530 sp=0x14037515500 pc=0x104915a40
github.com/goki/vgpu/vgpu.(*RenderFrame).SetSize(...)
	/Users/erdal/go/pkg/mod/github.com/goki/vgpu@v1.0.33/vgpu/renderframe.go:120
github.com/emer/eve/evev.(*View).RenderOffNode(0x106b7dc58?, {0x131957d80, 0x14026c02000}, 0x14000694420)
	/Users/erdal/go/pkg/mod/github.com/emer/eve@v0.9.3/evev/view.go:81 +0x220 fp=0x140375158b0 sp=0x14037515530 pc=0x105474fc0
github.com/emer/axon/examples/boa/armaze.(*GUI).GrabEyeImg(0x14000694380)
	/Users/erdal/dev/obelisk/axon/examples/boa/armaze/gui.go:596 +0x68 fp=0x14037515960 sp=0x140375158b0 pc=0x10547c618
github.com/emer/axon/examples/boa/armaze.(*GUI).UpdateWorldGUI(0x14000694380)
	/Users/erdal/dev/obelisk/axon/examples/boa/armaze/gui.go:697 +0xb8 fp=0x140375159c0 sp=0x14037515960 pc=0x10547d1f8
github.com/emer/axon/examples/boa/armaze.(*GUI).UpdateWorld(0x14000694380, 0x1054ca19b?, 0x14000694e00, 0x1?, 0x14037515a68?)
	/Users/erdal/dev/obelisk/axon/examples/boa/armaze/gui.go:674 +0xec fp=0x14037515a00 sp=0x140375159c0 pc=0x10547cfbc
main.(*Sim).UpdateEnvGUI(0x140005fe800, 0x5fef48?)
	/Users/erdal/dev/obelisk/axon/examples/boa/boa.go:1208 +0x584 fp=0x14037515ad0 sp=0x14037515a00 pc=0x1054918b4
main.(*Sim).ConfigLoops.func10()
	/Users/erdal/dev/obelisk/axon/examples/boa/boa.go:485 +0x24 fp=0x14037515af0 sp=0x14037515ad0 pc=0x10548a534
github.com/emer/emergent/looper.(*Manager).runLevel(0x1400352cb00, 0x2)
	/Users/erdal/go/pkg/mod/github.com/emer/emergent@v1.4.31-0.20230918190815-bbdd12cb842d/looper/manager.go:300 +0x5e4 fp=0x14037515c70 sp=0x14037515af0 pc=0x105331494
github.com/emer/emergent/looper.(*Manager).runLevel(0x1400352cb00, 0x1)
	/Users/erdal/go/pkg/mod/github.com/emer/emergent@v1.4.31-0.20230918190815-bbdd12cb842d/looper/manager.go:290 +0x384 fp=0x14037515df0 sp=0x14037515c70 pc=0x105331234
github.com/emer/emergent/looper.(*Manager).runLevel(0x1400352cb00, 0x0)
	/Users/erdal/go/pkg/mod/github.com/emer/emergent@v1.4.31-0.20230918190815-bbdd12cb842d/looper/manager.go:290 +0x384 fp=0x14037515f70 sp=0x14037515df0 pc=0x105331234
github.com/emer/emergent/looper.(*Manager).Cont(...)
	/Users/erdal/go/pkg/mod/github.com/emer/emergent@v1.4.31-0.20230918190815-bbdd12cb842d/looper/manager.go:232
github.com/emer/emergent/looper.(*Manager).Run(0x1400352cb00, 0x45a6494?)
	/Users/erdal/go/pkg/mod/github.com/emer/emergent@v1.4.31-0.20230918190815-bbdd12cb842d/looper/manager.go:215 +0x68 fp=0x14037515fa0 sp=0x14037515f70 pc=0x105330d38
github.com/emer/emergent/egui.(*GUI).AddLooperCtrl.func3.1()
	/Users/erdal/go/pkg/mod/github.com/emer/emergent@v1.4.31-0.20230918190815-bbdd12cb842d/egui/loopctrl.go:39 +0x2c fp=0x14037515fd0 sp=0x14037515fa0 pc=0x1053d308c
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.1/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x14037515fd0 sp=0x14037515fd0 pc=0x1045a6494
created by github.com/emer/emergent/egui.(*GUI).AddLooperCtrl.func3 in goroutine 7
	/Users/erdal/go/pkg/mod/github.com/emer/emergent@v1.4.31-0.20230918190815-bbdd12cb842d/egui/loopctrl.go:38 +0xb4

**Comment by rcoreilly** [comment]
fixed in new gui
